from django.urls import path, re_path
from .views import UserAccountViewSet, lent_books
from rest_framework import routers

# Initialize a router and register your view set
router = routers.SimpleRouter()
router.register(r"", UserAccountViewSet, basename="user-account")


# Retrieve the list of URL patterns generated by the router
urlpatterns = [
    # *router.get_urls(),
    path(
        "get_category/<str:category>/",
        UserAccountViewSet.as_view({"get": "get_books_by_category"}),
        name="get-category",
    ),
    path(
        "get_recomended_books/<str:category>/",
        UserAccountViewSet.as_view({"get": "get_books_by_category"}),
        name="get-category",
    ),
    path(
        "get_lent_books/",
        lent_books,
        name="get-category",
    ),
    path(
        "get_reserved_books/",
        UserAccountViewSet.as_view({"get": "get_reserved_book"}),
        name="lent_new_book",
    ),
    path(
        "lent/<str:id>/",
        UserAccountViewSet.as_view({"get": "check_lent"}),
        name="already-lend",
    ),
    path(
        "lend_new_book/<str:id>/",
        UserAccountViewSet.as_view({"post": "lend_new_book"}),
        name="lent_new_book",
    ),
    path(
        "reserved/<str:id>/",
        UserAccountViewSet.as_view({"get": "check_reserved"}),
        name="already-lend",
    ),
    path(
        "reserve_new_book/<str:id>/",
        UserAccountViewSet.as_view({"post": "reserve_new_book"}),
        name="reserve_new_book",
    ),
]
