# Generated by Django 4.2.10 on 2024-05-01 22:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('gender', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_lent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_locked', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_reserved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('number_of_people_rated', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('unlike', models.IntegerField()),
                ('loved', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('total_pages', models.IntegerField()),
                ('ISBN', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('lent', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='books/')),
                ('category', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='share.adminaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Reserved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(default=django.utils.timezone.now)),
                ('outlay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accured', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('unlocked', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='share.book')),
            ],
        ),
        migrations.CreateModel(
            name='Lend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(default=django.utils.timezone.now)),
                ('outlay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accured', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('exceeding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lend_books', to='share.book')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('faculty', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('matric_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('expected_year_of_graduation', models.IntegerField()),
                ('otp', models.IntegerField(default=0)),
                ('has_confirm_otp', models.BooleanField(default=False)),
                ('otp_expiration_time', models.IntegerField(default=0)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('locked_amount', models.IntegerField(default=0)),
                ('balance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='share.balance', verbose_name='balancemk')),
                ('lent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='share.lend', verbose_name='balancemk')),
                ('reserved', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='share.reserved', verbose_name='balancemk')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
