# Generated by Django 4.2.10 on 2024-05-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_adminaccount_otp_remove_lend_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccount',
            name='full_name',
            field=models.CharField(default='solamide', max_length=100),
            preserve_default=False,
        ),
    ]
