# Generated by Django 4.2.10 on 2024-05-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_adminaccount_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaccount',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
