# Generated by Django 4.2.10 on 2024-05-07 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_alter_adminaccount_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccount',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminaccount',
            name='is_supper_admin',
            field=models.BooleanField(default=True),
        ),
    ]
