# Generated by Django 4.2.10 on 2024-05-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_adminaccount_date_adminaccount_is_supper_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='loved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_people_rated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='unlike',
            field=models.IntegerField(default=0),
        ),
    ]
