# Generated by Django 4.2.10 on 2024-06-16 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_default_userpreferance(apps, schema_editor):
    UserPreferance = apps.get_model("share", "UserPreferance")
    UserAccount = apps.get_model("share", "UserAccount")

    # Create a default UserPreferance instance
    default_preference = UserPreferance.objects.create(category_selection="Science")

    # Assign the default preference to all existing UserAccount entries
    for user_account in UserAccount.objects.all():
        user_account.preferance = default_preference
        user_account.save()


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0006_alter_book_likes_alter_book_loved_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_selection",
                    models.CharField(default="Science", max_length=100),
                ),
            ],
        ),
        migrations.AddField(
            model_name="balance",
            name="number_of_facucet",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="book",
            name="group",
            field=models.CharField(default="prediction", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="adminaccount",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="balance",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="share.balance"
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="lent",
            field=models.ManyToManyField(to="share.lend"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="reserved",
            field=models.ManyToManyField(to="share.reserved"),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                ("message", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LEND", "LEND"),
                            ("RESERVED", "RESERVED"),
                            ("RECHARGE", "RECHARGE"),
                            ("CHECKIN", "CHECKIN"),
                            ("CHECKOUT", "CHECKOUT"),
                            ("DEBIT", "DEBIT"),
                            ("DUE", "DUE"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="useraccount",
            name="preferance",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="share.userpreferance",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(create_default_userpreferance),
    ]
