# Generated by Django 4.2.10 on 2024-06-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0007_userpreferance_balance_number_of_facucet_book_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
