# Generated by Django 4.2.10 on 2024-07-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0010_remove_lend_accured_remove_lend_exceeding_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publicatio_date',
            new_name='publication_date',
        ),
    ]
