# Generated by Django 4.2.10 on 2024-07-27 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0011_rename_publicatio_date_book_publication_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="lent",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="reserved",
        ),
        migrations.AddField(
            model_name="lend",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        # migrations.AddField(
        #     model_name='reserved',
        #     name='end_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name="reserved",
        #     name="start_date",
        #     field=models.DateField(blank=True, null=True),
        # ),
        migrations.AddField(
            model_name="reserved",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useraccount",
            name="lentReserved",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="reservedBook",
            field=models.IntegerField(default=0),
        ),
    ]
