# Generated by Django 4.2.10 on 2024-07-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0012_remove_useraccount_lent_remove_useraccount_reserved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserved',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserved',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
