# Generated by Django 4.2.10 on 2024-07-27 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0014_remove_reserved_user_reserved_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='reserved',
            new_name='reserve',
        ),
        migrations.RemoveField(
            model_name='reserved',
            name='book',
        ),
        migrations.RemoveField(
            model_name='reserved',
            name='user',
        ),
        migrations.AddField(
            model_name='reserved',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='share.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserved',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
