# Generated by Django 4.2.10 on 2024-07-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0015_rename_reserved_book_reserve_remove_reserved_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lend',
            name='book',
        ),
        migrations.AddField(
            model_name='lend',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='share.book'),
            preserve_default=False,
        ),
    ]
