# Generated by Django 4.2.10 on 2024-07-28 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0017_remove_lend_cost_per_day_remove_lend_is_returned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserved',
            name='borrow_date',
        ),
        migrations.RemoveField(
            model_name='reserved',
            name='end_date',
        ),
        migrations.AddField(
            model_name='reserved',
            name='reserve_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
